#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34014
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



public partial class SLSdb : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAuthors(Authors instance);
  partial void UpdateAuthors(Authors instance);
  partial void DeleteAuthors(Authors instance);
  partial void InsertBooks(Books instance);
  partial void UpdateBooks(Books instance);
  partial void DeleteBooks(Books instance);
  partial void InsertBorrows(Borrows instance);
  partial void UpdateBorrows(Borrows instance);
  partial void DeleteBorrows(Borrows instance);
  partial void InsertCategories(Categories instance);
  partial void UpdateCategories(Categories instance);
  partial void DeleteCategories(Categories instance);
  partial void InsertPublishers(Publishers instance);
  partial void UpdatePublishers(Publishers instance);
  partial void DeletePublishers(Publishers instance);
  partial void InsertReservations(Reservations instance);
  partial void UpdateReservations(Reservations instance);
  partial void DeleteReservations(Reservations instance);
  partial void InsertUsers(Users instance);
  partial void UpdateUsers(Users instance);
  partial void DeleteUsers(Users instance);
  #endregion
	
	public SLSdb(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SLSdb(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SLSdb(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SLSdb(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Authors> Authors
	{
		get
		{
			return this.GetTable<Authors>();
		}
	}
	
	public System.Data.Linq.Table<Book_authors> Book_authors
	{
		get
		{
			return this.GetTable<Book_authors>();
		}
	}
	
	public System.Data.Linq.Table<Book_categories> Book_categories
	{
		get
		{
			return this.GetTable<Book_categories>();
		}
	}
	
	public System.Data.Linq.Table<Books> Books
	{
		get
		{
			return this.GetTable<Books>();
		}
	}
	
	public System.Data.Linq.Table<Borrows> Borrows
	{
		get
		{
			return this.GetTable<Borrows>();
		}
	}
	
	public System.Data.Linq.Table<Categories> Categories
	{
		get
		{
			return this.GetTable<Categories>();
		}
	}
	
	public System.Data.Linq.Table<Publishers> Publishers
	{
		get
		{
			return this.GetTable<Publishers>();
		}
	}
	
	public System.Data.Linq.Table<Reservations> Reservations
	{
		get
		{
			return this.GetTable<Reservations>();
		}
	}
	
	public System.Data.Linq.Table<Users> Users
	{
		get
		{
			return this.GetTable<Users>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="authors")]
public partial class Authors : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Firstname;
	
	private string _Surname;
	
	private System.Nullable<System.DateTime> _Date_of_birth;
	
	private System.Nullable<System.DateTime> _Date_of_death;
	
	private string _Description;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnDate_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_of_birthChanged();
    partial void OnDate_of_deathChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_of_deathChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
	
	public Authors()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="firstname", Storage="_Firstname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Firstname
	{
		get
		{
			return this._Firstname;
		}
		set
		{
			if ((this._Firstname != value))
			{
				this.OnFirstnameChanging(value);
				this.SendPropertyChanging();
				this._Firstname = value;
				this.SendPropertyChanged("Firstname");
				this.OnFirstnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="surname", Storage="_Surname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Surname
	{
		get
		{
			return this._Surname;
		}
		set
		{
			if ((this._Surname != value))
			{
				this.OnSurnameChanging(value);
				this.SendPropertyChanging();
				this._Surname = value;
				this.SendPropertyChanged("Surname");
				this.OnSurnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="date_of_birth", Storage="_Date_of_birth", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date_of_birth
	{
		get
		{
			return this._Date_of_birth;
		}
		set
		{
			if ((this._Date_of_birth != value))
			{
				this.OnDate_of_birthChanging(value);
				this.SendPropertyChanging();
				this._Date_of_birth = value;
				this.SendPropertyChanged("Date_of_birth");
				this.OnDate_of_birthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="date_of_death", Storage="_Date_of_death", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date_of_death
	{
		get
		{
			return this._Date_of_death;
		}
		set
		{
			if ((this._Date_of_death != value))
			{
				this.OnDate_of_deathChanging(value);
				this.SendPropertyChanging();
				this._Date_of_death = value;
				this.SendPropertyChanged("Date_of_death");
				this.OnDate_of_deathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="description", Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="book_authors")]
public partial class Book_authors
{
	
	private int _Book_id_fk;
	
	private int _Author_id_fk;
	
	private int _Ord;
	
	public Book_authors()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="book_id_fk", Storage="_Book_id_fk", DbType="Int NOT NULL")]
	public int Book_id_fk
	{
		get
		{
			return this._Book_id_fk;
		}
		set
		{
			if ((this._Book_id_fk != value))
			{
				this._Book_id_fk = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="author_id_fk", Storage="_Author_id_fk", DbType="Int NOT NULL")]
	public int Author_id_fk
	{
		get
		{
			return this._Author_id_fk;
		}
		set
		{
			if ((this._Author_id_fk != value))
			{
				this._Author_id_fk = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ord", Storage="_Ord", DbType="Int NOT NULL")]
	public int Ord
	{
		get
		{
			return this._Ord;
		}
		set
		{
			if ((this._Ord != value))
			{
				this._Ord = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="book_categories")]
public partial class Book_categories
{
	
	private int _Book_id_fk;
	
	private int _Category_id_fk;
	
	public Book_categories()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="book_id_fk", Storage="_Book_id_fk", DbType="Int NOT NULL")]
	public int Book_id_fk
	{
		get
		{
			return this._Book_id_fk;
		}
		set
		{
			if ((this._Book_id_fk != value))
			{
				this._Book_id_fk = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="category_id_fk", Storage="_Category_id_fk", DbType="Int NOT NULL")]
	public int Category_id_fk
	{
		get
		{
			return this._Category_id_fk;
		}
		set
		{
			if ((this._Category_id_fk != value))
			{
				this._Category_id_fk = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="books")]
public partial class Books : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Isbn;
	
	private System.Nullable<int> _Publisher_id_fk;
	
	private System.Nullable<System.DateTime> _Publish_date;
	
	private string _Publish_city;
	
	private System.Nullable<int> _Publish_edition;
	
	private string _Title;
	
	private string _Cover;
	
	private string _Table_of_contents;
	
	private string _Language;
	
	private string _Description;
	
	private int _Available_copies;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIsbnChanging(string value);
    partial void OnIsbnChanged();
    partial void OnPublisher_id_fkChanging(System.Nullable<int> value);
    partial void OnPublisher_id_fkChanged();
    partial void OnPublish_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnPublish_dateChanged();
    partial void OnPublish_cityChanging(string value);
    partial void OnPublish_cityChanged();
    partial void OnPublish_editionChanging(System.Nullable<int> value);
    partial void OnPublish_editionChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnCoverChanging(string value);
    partial void OnCoverChanged();
    partial void OnTable_of_contentsChanging(string value);
    partial void OnTable_of_contentsChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAvailable_copiesChanging(int value);
    partial void OnAvailable_copiesChanged();
    #endregion
	
	public Books()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="isbn", Storage="_Isbn", DbType="NChar(20) NOT NULL", CanBeNull=false)]
	public string Isbn
	{
		get
		{
			return this._Isbn;
		}
		set
		{
			if ((this._Isbn != value))
			{
				this.OnIsbnChanging(value);
				this.SendPropertyChanging();
				this._Isbn = value;
				this.SendPropertyChanged("Isbn");
				this.OnIsbnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="publisher_id_fk", Storage="_Publisher_id_fk", DbType="Int")]
	public System.Nullable<int> Publisher_id_fk
	{
		get
		{
			return this._Publisher_id_fk;
		}
		set
		{
			if ((this._Publisher_id_fk != value))
			{
				this.OnPublisher_id_fkChanging(value);
				this.SendPropertyChanging();
				this._Publisher_id_fk = value;
				this.SendPropertyChanged("Publisher_id_fk");
				this.OnPublisher_id_fkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="publish_date", Storage="_Publish_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Publish_date
	{
		get
		{
			return this._Publish_date;
		}
		set
		{
			if ((this._Publish_date != value))
			{
				this.OnPublish_dateChanging(value);
				this.SendPropertyChanging();
				this._Publish_date = value;
				this.SendPropertyChanged("Publish_date");
				this.OnPublish_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="publish_city", Storage="_Publish_city", DbType="NVarChar(50)")]
	public string Publish_city
	{
		get
		{
			return this._Publish_city;
		}
		set
		{
			if ((this._Publish_city != value))
			{
				this.OnPublish_cityChanging(value);
				this.SendPropertyChanging();
				this._Publish_city = value;
				this.SendPropertyChanged("Publish_city");
				this.OnPublish_cityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="publish_edition", Storage="_Publish_edition", DbType="Int")]
	public System.Nullable<int> Publish_edition
	{
		get
		{
			return this._Publish_edition;
		}
		set
		{
			if ((this._Publish_edition != value))
			{
				this.OnPublish_editionChanging(value);
				this.SendPropertyChanging();
				this._Publish_edition = value;
				this.SendPropertyChanged("Publish_edition");
				this.OnPublish_editionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="title", Storage="_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cover", Storage="_Cover", DbType="NVarChar(255)")]
	public string Cover
	{
		get
		{
			return this._Cover;
		}
		set
		{
			if ((this._Cover != value))
			{
				this.OnCoverChanging(value);
				this.SendPropertyChanging();
				this._Cover = value;
				this.SendPropertyChanged("Cover");
				this.OnCoverChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="table_of_contents", Storage="_Table_of_contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Table_of_contents
	{
		get
		{
			return this._Table_of_contents;
		}
		set
		{
			if ((this._Table_of_contents != value))
			{
				this.OnTable_of_contentsChanging(value);
				this.SendPropertyChanging();
				this._Table_of_contents = value;
				this.SendPropertyChanged("Table_of_contents");
				this.OnTable_of_contentsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="language", Storage="_Language", DbType="NVarChar(50)")]
	public string Language
	{
		get
		{
			return this._Language;
		}
		set
		{
			if ((this._Language != value))
			{
				this.OnLanguageChanging(value);
				this.SendPropertyChanging();
				this._Language = value;
				this.SendPropertyChanged("Language");
				this.OnLanguageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="description", Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="available_copies", Storage="_Available_copies", DbType="Int NOT NULL")]
	public int Available_copies
	{
		get
		{
			return this._Available_copies;
		}
		set
		{
			if ((this._Available_copies != value))
			{
				this.OnAvailable_copiesChanging(value);
				this.SendPropertyChanging();
				this._Available_copies = value;
				this.SendPropertyChanged("Available_copies");
				this.OnAvailable_copiesChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="borrows")]
public partial class Borrows : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _Book_id_fk;
	
	private int _User_id_fk;
	
	private System.DateTime _From_date;
	
	private System.DateTime _To_date;
	
	private int _Prolong_cnt;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBook_id_fkChanging(int value);
    partial void OnBook_id_fkChanged();
    partial void OnUser_id_fkChanging(int value);
    partial void OnUser_id_fkChanged();
    partial void OnFrom_dateChanging(System.DateTime value);
    partial void OnFrom_dateChanged();
    partial void OnTo_dateChanging(System.DateTime value);
    partial void OnTo_dateChanged();
    partial void OnProlong_cntChanging(int value);
    partial void OnProlong_cntChanged();
    #endregion
	
	public Borrows()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="book_id_fk", Storage="_Book_id_fk", DbType="Int NOT NULL")]
	public int Book_id_fk
	{
		get
		{
			return this._Book_id_fk;
		}
		set
		{
			if ((this._Book_id_fk != value))
			{
				this.OnBook_id_fkChanging(value);
				this.SendPropertyChanging();
				this._Book_id_fk = value;
				this.SendPropertyChanged("Book_id_fk");
				this.OnBook_id_fkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="user_id_fk", Storage="_User_id_fk", DbType="Int NOT NULL")]
	public int User_id_fk
	{
		get
		{
			return this._User_id_fk;
		}
		set
		{
			if ((this._User_id_fk != value))
			{
				this.OnUser_id_fkChanging(value);
				this.SendPropertyChanging();
				this._User_id_fk = value;
				this.SendPropertyChanged("User_id_fk");
				this.OnUser_id_fkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="from_date", Storage="_From_date", DbType="DateTime NOT NULL")]
	public System.DateTime From_date
	{
		get
		{
			return this._From_date;
		}
		set
		{
			if ((this._From_date != value))
			{
				this.OnFrom_dateChanging(value);
				this.SendPropertyChanging();
				this._From_date = value;
				this.SendPropertyChanged("From_date");
				this.OnFrom_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="to_date", Storage="_To_date", DbType="DateTime NOT NULL")]
	public System.DateTime To_date
	{
		get
		{
			return this._To_date;
		}
		set
		{
			if ((this._To_date != value))
			{
				this.OnTo_dateChanging(value);
				this.SendPropertyChanging();
				this._To_date = value;
				this.SendPropertyChanged("To_date");
				this.OnTo_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="prolong_cnt", Storage="_Prolong_cnt", DbType="Int NOT NULL")]
	public int Prolong_cnt
	{
		get
		{
			return this._Prolong_cnt;
		}
		set
		{
			if ((this._Prolong_cnt != value))
			{
				this.OnProlong_cntChanging(value);
				this.SendPropertyChanging();
				this._Prolong_cnt = value;
				this.SendPropertyChanged("Prolong_cnt");
				this.OnProlong_cntChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="categories")]
public partial class Categories : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
	
	public Categories()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="name", Storage="_Name", DbType="NVarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="publishers")]
public partial class Publishers : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
	
	public Publishers()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="name", Storage="_Name", DbType="NVarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="reservations")]
public partial class Reservations : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _Book_id_fk;
	
	private int _User_id_fk;
	
	private System.DateTime _Reservation_date;
	
	private System.Nullable<int> _Queue_position;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBook_id_fkChanging(int value);
    partial void OnBook_id_fkChanged();
    partial void OnUser_id_fkChanging(int value);
    partial void OnUser_id_fkChanged();
    partial void OnReservation_dateChanging(System.DateTime value);
    partial void OnReservation_dateChanged();
    partial void OnQueue_positionChanging(System.Nullable<int> value);
    partial void OnQueue_positionChanged();
    #endregion
	
	public Reservations()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="book_id_fk", Storage="_Book_id_fk", DbType="Int NOT NULL")]
	public int Book_id_fk
	{
		get
		{
			return this._Book_id_fk;
		}
		set
		{
			if ((this._Book_id_fk != value))
			{
				this.OnBook_id_fkChanging(value);
				this.SendPropertyChanging();
				this._Book_id_fk = value;
				this.SendPropertyChanged("Book_id_fk");
				this.OnBook_id_fkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="user_id_fk", Storage="_User_id_fk", DbType="Int NOT NULL")]
	public int User_id_fk
	{
		get
		{
			return this._User_id_fk;
		}
		set
		{
			if ((this._User_id_fk != value))
			{
				this.OnUser_id_fkChanging(value);
				this.SendPropertyChanging();
				this._User_id_fk = value;
				this.SendPropertyChanged("User_id_fk");
				this.OnUser_id_fkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="reservation_date", Storage="_Reservation_date", DbType="DateTime NOT NULL")]
	public System.DateTime Reservation_date
	{
		get
		{
			return this._Reservation_date;
		}
		set
		{
			if ((this._Reservation_date != value))
			{
				this.OnReservation_dateChanging(value);
				this.SendPropertyChanging();
				this._Reservation_date = value;
				this.SendPropertyChanged("Reservation_date");
				this.OnReservation_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="queue_position", Storage="_Queue_position", DbType="Int")]
	public System.Nullable<int> Queue_position
	{
		get
		{
			return this._Queue_position;
		}
		set
		{
			if ((this._Queue_position != value))
			{
				this.OnQueue_positionChanging(value);
				this.SendPropertyChanging();
				this._Queue_position = value;
				this.SendPropertyChanged("Queue_position");
				this.OnQueue_positionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="users")]
public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _Role_id_fk;
	
	private string _Login;
	
	private string _Email;
	
	private string _Firstname;
	
	private string _Surname;
	
	private int _Phone;
	
	private string _Passwd;
	
	private int _Incorrect_login_cnt;
	
	private string _Last_login_info;
	
	private string _Token;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRole_id_fkChanging(int value);
    partial void OnRole_id_fkChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnPhoneChanging(int value);
    partial void OnPhoneChanged();
    partial void OnPasswdChanging(string value);
    partial void OnPasswdChanged();
    partial void OnIncorrect_login_cntChanging(int value);
    partial void OnIncorrect_login_cntChanged();
    partial void OnLast_login_infoChanging(string value);
    partial void OnLast_login_infoChanged();
    partial void OnTokenChanging(string value);
    partial void OnTokenChanged();
    #endregion
	
	public Users()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="role_id_fk", Storage="_Role_id_fk", DbType="Int NOT NULL")]
	public int Role_id_fk
	{
		get
		{
			return this._Role_id_fk;
		}
		set
		{
			if ((this._Role_id_fk != value))
			{
				this.OnRole_id_fkChanging(value);
				this.SendPropertyChanging();
				this._Role_id_fk = value;
				this.SendPropertyChanged("Role_id_fk");
				this.OnRole_id_fkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="login", Storage="_Login", DbType="NChar(20) NOT NULL", CanBeNull=false)]
	public string Login
	{
		get
		{
			return this._Login;
		}
		set
		{
			if ((this._Login != value))
			{
				this.OnLoginChanging(value);
				this.SendPropertyChanging();
				this._Login = value;
				this.SendPropertyChanged("Login");
				this.OnLoginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="email", Storage="_Email", DbType="NChar(50) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="firstname", Storage="_Firstname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Firstname
	{
		get
		{
			return this._Firstname;
		}
		set
		{
			if ((this._Firstname != value))
			{
				this.OnFirstnameChanging(value);
				this.SendPropertyChanging();
				this._Firstname = value;
				this.SendPropertyChanged("Firstname");
				this.OnFirstnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="surname", Storage="_Surname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Surname
	{
		get
		{
			return this._Surname;
		}
		set
		{
			if ((this._Surname != value))
			{
				this.OnSurnameChanging(value);
				this.SendPropertyChanging();
				this._Surname = value;
				this.SendPropertyChanged("Surname");
				this.OnSurnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="phone", Storage="_Phone", DbType="Int NOT NULL")]
	public int Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="passwd", Storage="_Passwd", DbType="NChar(40) NOT NULL", CanBeNull=false)]
	public string Passwd
	{
		get
		{
			return this._Passwd;
		}
		set
		{
			if ((this._Passwd != value))
			{
				this.OnPasswdChanging(value);
				this.SendPropertyChanging();
				this._Passwd = value;
				this.SendPropertyChanged("Passwd");
				this.OnPasswdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="incorrect_login_cnt", Storage="_Incorrect_login_cnt", DbType="Int NOT NULL")]
	public int Incorrect_login_cnt
	{
		get
		{
			return this._Incorrect_login_cnt;
		}
		set
		{
			if ((this._Incorrect_login_cnt != value))
			{
				this.OnIncorrect_login_cntChanging(value);
				this.SendPropertyChanging();
				this._Incorrect_login_cnt = value;
				this.SendPropertyChanged("Incorrect_login_cnt");
				this.OnIncorrect_login_cntChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="last_login_info", Storage="_Last_login_info", DbType="NVarChar(255)")]
	public string Last_login_info
	{
		get
		{
			return this._Last_login_info;
		}
		set
		{
			if ((this._Last_login_info != value))
			{
				this.OnLast_login_infoChanging(value);
				this.SendPropertyChanging();
				this._Last_login_info = value;
				this.SendPropertyChanged("Last_login_info");
				this.OnLast_login_infoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="token", Storage="_Token", DbType="NVarChar(255)")]
	public string Token
	{
		get
		{
			return this._Token;
		}
		set
		{
			if ((this._Token != value))
			{
				this.OnTokenChanging(value);
				this.SendPropertyChanging();
				this._Token = value;
				this.SendPropertyChanged("Token");
				this.OnTokenChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
