//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace SLS.Mobile.SLSMobile {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    public partial class Book : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int available_copiesField;
        
        private string coverField;
        
        private string descriptionField;
        
        private int idField;
        
        private string isbnField;
        
        private string languageField;
        
        private string publish_cityField;
        
        private System.Nullable<System.DateTime> publish_dateField;
        
        private System.Nullable<int> publish_editionField;
        
        private string table_of_contentsField;
        
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_copies {
            get {
                return this.available_copiesField;
            }
            set {
                if ((this.available_copiesField.Equals(value) != true)) {
                    this.available_copiesField = value;
                    this.RaisePropertyChanged("available_copies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cover {
            get {
                return this.coverField;
            }
            set {
                if ((object.ReferenceEquals(this.coverField, value) != true)) {
                    this.coverField = value;
                    this.RaisePropertyChanged("cover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                if ((object.ReferenceEquals(this.isbnField, value) != true)) {
                    this.isbnField = value;
                    this.RaisePropertyChanged("isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string publish_city {
            get {
                return this.publish_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.publish_cityField, value) != true)) {
                    this.publish_cityField = value;
                    this.RaisePropertyChanged("publish_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> publish_date {
            get {
                return this.publish_dateField;
            }
            set {
                if ((this.publish_dateField.Equals(value) != true)) {
                    this.publish_dateField = value;
                    this.RaisePropertyChanged("publish_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> publish_edition {
            get {
                return this.publish_editionField;
            }
            set {
                if ((this.publish_editionField.Equals(value) != true)) {
                    this.publish_editionField = value;
                    this.RaisePropertyChanged("publish_edition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string table_of_contents {
            get {
                return this.table_of_contentsField;
            }
            set {
                if ((object.ReferenceEquals(this.table_of_contentsField, value) != true)) {
                    this.table_of_contentsField = value;
                    this.RaisePropertyChanged("table_of_contents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLSMobile.ISLSMobileService")]
    public interface ISLSMobileService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISLSMobileService/GetBooksForUser", ReplyAction="http://tempuri.org/ISLSMobileService/GetBooksForUserResponse")]
        System.IAsyncResult BeginGetBooksForUser(int userId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SLS.Mobile.SLSMobile.Book> EndGetBooksForUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISLSMobileService/BorrowBook", ReplyAction="http://tempuri.org/ISLSMobileService/BorrowBookResponse")]
        System.IAsyncResult BeginBorrowBook(int userId, int bookId, System.AsyncCallback callback, object asyncState);
        
        bool EndBorrowBook(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISLSMobileService/ReturnBook", ReplyAction="http://tempuri.org/ISLSMobileService/ReturnBookResponse")]
        System.IAsyncResult BeginReturnBook(int userId, int bookId, System.AsyncCallback callback, object asyncState);
        
        bool EndReturnBook(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLSMobileServiceChannel : SLS.Mobile.SLSMobile.ISLSMobileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBooksForUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBooksForUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SLS.Mobile.SLSMobile.Book> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SLS.Mobile.SLSMobile.Book>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BorrowBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BorrowBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReturnBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReturnBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLSMobileServiceClient : System.ServiceModel.ClientBase<SLS.Mobile.SLSMobile.ISLSMobileService>, SLS.Mobile.SLSMobile.ISLSMobileService {
        
        private BeginOperationDelegate onBeginGetBooksForUserDelegate;
        
        private EndOperationDelegate onEndGetBooksForUserDelegate;
        
        private System.Threading.SendOrPostCallback onGetBooksForUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginBorrowBookDelegate;
        
        private EndOperationDelegate onEndBorrowBookDelegate;
        
        private System.Threading.SendOrPostCallback onBorrowBookCompletedDelegate;
        
        private BeginOperationDelegate onBeginReturnBookDelegate;
        
        private EndOperationDelegate onEndReturnBookDelegate;
        
        private System.Threading.SendOrPostCallback onReturnBookCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SLSMobileServiceClient() {
        }
        
        public SLSMobileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLSMobileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLSMobileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLSMobileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetBooksForUserCompletedEventArgs> GetBooksForUserCompleted;
        
        public event System.EventHandler<BorrowBookCompletedEventArgs> BorrowBookCompleted;
        
        public event System.EventHandler<ReturnBookCompletedEventArgs> ReturnBookCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLS.Mobile.SLSMobile.ISLSMobileService.BeginGetBooksForUser(int userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBooksForUser(userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SLS.Mobile.SLSMobile.Book> SLS.Mobile.SLSMobile.ISLSMobileService.EndGetBooksForUser(System.IAsyncResult result) {
            return base.Channel.EndGetBooksForUser(result);
        }
        
        private System.IAsyncResult OnBeginGetBooksForUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            return ((SLS.Mobile.SLSMobile.ISLSMobileService)(this)).BeginGetBooksForUser(userId, callback, asyncState);
        }
        
        private object[] OnEndGetBooksForUser(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SLS.Mobile.SLSMobile.Book> retVal = ((SLS.Mobile.SLSMobile.ISLSMobileService)(this)).EndGetBooksForUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBooksForUserCompleted(object state) {
            if ((this.GetBooksForUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBooksForUserCompleted(this, new GetBooksForUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBooksForUserAsync(int userId) {
            this.GetBooksForUserAsync(userId, null);
        }
        
        public void GetBooksForUserAsync(int userId, object userState) {
            if ((this.onBeginGetBooksForUserDelegate == null)) {
                this.onBeginGetBooksForUserDelegate = new BeginOperationDelegate(this.OnBeginGetBooksForUser);
            }
            if ((this.onEndGetBooksForUserDelegate == null)) {
                this.onEndGetBooksForUserDelegate = new EndOperationDelegate(this.OnEndGetBooksForUser);
            }
            if ((this.onGetBooksForUserCompletedDelegate == null)) {
                this.onGetBooksForUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBooksForUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetBooksForUserDelegate, new object[] {
                        userId}, this.onEndGetBooksForUserDelegate, this.onGetBooksForUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLS.Mobile.SLSMobile.ISLSMobileService.BeginBorrowBook(int userId, int bookId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBorrowBook(userId, bookId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SLS.Mobile.SLSMobile.ISLSMobileService.EndBorrowBook(System.IAsyncResult result) {
            return base.Channel.EndBorrowBook(result);
        }
        
        private System.IAsyncResult OnBeginBorrowBook(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            int bookId = ((int)(inValues[1]));
            return ((SLS.Mobile.SLSMobile.ISLSMobileService)(this)).BeginBorrowBook(userId, bookId, callback, asyncState);
        }
        
        private object[] OnEndBorrowBook(System.IAsyncResult result) {
            bool retVal = ((SLS.Mobile.SLSMobile.ISLSMobileService)(this)).EndBorrowBook(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBorrowBookCompleted(object state) {
            if ((this.BorrowBookCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BorrowBookCompleted(this, new BorrowBookCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BorrowBookAsync(int userId, int bookId) {
            this.BorrowBookAsync(userId, bookId, null);
        }
        
        public void BorrowBookAsync(int userId, int bookId, object userState) {
            if ((this.onBeginBorrowBookDelegate == null)) {
                this.onBeginBorrowBookDelegate = new BeginOperationDelegate(this.OnBeginBorrowBook);
            }
            if ((this.onEndBorrowBookDelegate == null)) {
                this.onEndBorrowBookDelegate = new EndOperationDelegate(this.OnEndBorrowBook);
            }
            if ((this.onBorrowBookCompletedDelegate == null)) {
                this.onBorrowBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBorrowBookCompleted);
            }
            base.InvokeAsync(this.onBeginBorrowBookDelegate, new object[] {
                        userId,
                        bookId}, this.onEndBorrowBookDelegate, this.onBorrowBookCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLS.Mobile.SLSMobile.ISLSMobileService.BeginReturnBook(int userId, int bookId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReturnBook(userId, bookId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SLS.Mobile.SLSMobile.ISLSMobileService.EndReturnBook(System.IAsyncResult result) {
            return base.Channel.EndReturnBook(result);
        }
        
        private System.IAsyncResult OnBeginReturnBook(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            int bookId = ((int)(inValues[1]));
            return ((SLS.Mobile.SLSMobile.ISLSMobileService)(this)).BeginReturnBook(userId, bookId, callback, asyncState);
        }
        
        private object[] OnEndReturnBook(System.IAsyncResult result) {
            bool retVal = ((SLS.Mobile.SLSMobile.ISLSMobileService)(this)).EndReturnBook(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReturnBookCompleted(object state) {
            if ((this.ReturnBookCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReturnBookCompleted(this, new ReturnBookCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReturnBookAsync(int userId, int bookId) {
            this.ReturnBookAsync(userId, bookId, null);
        }
        
        public void ReturnBookAsync(int userId, int bookId, object userState) {
            if ((this.onBeginReturnBookDelegate == null)) {
                this.onBeginReturnBookDelegate = new BeginOperationDelegate(this.OnBeginReturnBook);
            }
            if ((this.onEndReturnBookDelegate == null)) {
                this.onEndReturnBookDelegate = new EndOperationDelegate(this.OnEndReturnBook);
            }
            if ((this.onReturnBookCompletedDelegate == null)) {
                this.onReturnBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReturnBookCompleted);
            }
            base.InvokeAsync(this.onBeginReturnBookDelegate, new object[] {
                        userId,
                        bookId}, this.onEndReturnBookDelegate, this.onReturnBookCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SLS.Mobile.SLSMobile.ISLSMobileService CreateChannel() {
            return new SLSMobileServiceClientChannel(this);
        }
        
        private class SLSMobileServiceClientChannel : ChannelBase<SLS.Mobile.SLSMobile.ISLSMobileService>, SLS.Mobile.SLSMobile.ISLSMobileService {
            
            public SLSMobileServiceClientChannel(System.ServiceModel.ClientBase<SLS.Mobile.SLSMobile.ISLSMobileService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetBooksForUser(int userId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userId;
                System.IAsyncResult _result = base.BeginInvoke("GetBooksForUser", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SLS.Mobile.SLSMobile.Book> EndGetBooksForUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SLS.Mobile.SLSMobile.Book> _result = ((System.Collections.ObjectModel.ObservableCollection<SLS.Mobile.SLSMobile.Book>)(base.EndInvoke("GetBooksForUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginBorrowBook(int userId, int bookId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = userId;
                _args[1] = bookId;
                System.IAsyncResult _result = base.BeginInvoke("BorrowBook", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndBorrowBook(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("BorrowBook", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginReturnBook(int userId, int bookId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = userId;
                _args[1] = bookId;
                System.IAsyncResult _result = base.BeginInvoke("ReturnBook", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndReturnBook(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("ReturnBook", _args, result)));
                return _result;
            }
        }
    }
}
